### ISSUE TITLE
what does this project do and why its on my trending

### ISSUE THREAD

**Issue by drinktoomuchsax** [ProgrammingHero1/B9A1-New-Year-New-Mission#1]

**Comment by miaoerduo** [comment]
+1

**Comment by gobylor** [comment]
+1

**Comment by PeachyBer** [comment]
+1

**Comment by JoshuaKasa** [comment]
i swear 😭

**Comment by JoshuaKasa** [comment]
+1

**Comment by JoshuaKasa** [comment]
actually, I might know why. They're (as I can read from their bio) a [big learning platform](https://web.programming-hero.com/home) from Bangladesh. They **also** teach Figma and make courses about it. They probably just released a new couse or video teaching how to make some kind of "New Year Design" design or project and posted the link of the project source code. A lot of people probably bought this course, watched the video and starred this repository, GitHub saw that the project, in only a few days went, from 0 to more than 200 stars and therefore recommended it to everyone. 

EDIT: You can also see how many projects they have and their kind of videos, they get more than 800k views at time, so yeah, I guess my theory makes sense.

**Comment by miaoerduo** [comment]
> actually, I might know why. They're (as I can read from their bio) a [big learning platform](https://web.programming-hero.com/home) from Bangladesh. They **also** teach Figma and make courses about it. They probably just released a new couse or video teaching how to make some kind of "New Year Design" design or project and posted the link of the project source code. A lot of people probably bought this course, watched the video and starred this repository, GitHub saw that the project, in only a few days went, from 0 to more than 200 stars and therefore recommended it to everyone.
> 
> EDIT: You can also see how many projects they have and their kind of videos, they get more than 800k views at time, so yeah, I guess my theory makes sense.

oh yeah, make sense. I used to think it's some new ads service...

**Comment by engyasin** [comment]
The moral of the story is:  You don't have to make something big, just aim lower, lol

**Comment by Yeeler** [comment]
Should add context of the tutorial with some screenshots. It might get you more students from github.
